version: '3.7'

services:
  besu-node1:
    image: hyperledger/besu:latest
    container_name: besu-node1
    volumes:
      - ./node1:/var/lib/besu
      - ./keys:/opt/keys
      - ./genesis:/opt/genesis
    command:
      - "--genesis-file=/opt/genesis/genesis.json"
      - "--data-path=/var/lib/besu"
      - "--p2p-port=30303"
      - "--rpc-http-enabled"
      - "--rpc-http-host=0.0.0.0"
      - "--rpc-http-port=8545"
      - "--rpc-ws-enabled"
      - "--rpc-ws-host=0.0.0.0"
      - "--rpc-ws-port=8546"
    ports:
      - "8545:8545"
      - "30303:30303"

  besu-node2:
    image: hyperledger/besu:latest
    container_name: besu-node2
    volumes:
      - ./node2:/var/lib/besu
      - ./keys:/opt/keys
      - ./genesis:/opt/genesis
    command:
      - "--genesis-file=/opt/genesis/genesis.json"
      - "--data-path=/var/lib/besu"
      - "--p2p-port=30303"
      - "--rpc-http-enabled"
      - "--rpc-http-host=0.0.0.0"
      - "--rpc-http-port=8545"
      - "--rpc-ws-enabled"
      - "--rpc-ws-host=0.0.0.0"
      - "--rpc-ws-port=8546"
    ports:
      - "8546:8545"
      - "30304:30303"

  besu-node3:
    image: hyperledger/besu:latest
    container_name: besu-node3
    volumes:
      - ./node3:/var/lib/besu
      - ./keys:/opt/keys
      - ./genesis:/opt/genesis
    command:
      - "--genesis-file=/opt/genesis/genesis.json"
      - "--data-path=/var/lib/besu"
      - "--p2p-port=30303"
      - "--rpc-http-enabled"
      - "--rpc-http-host=0.0.0.0"
      - "--rpc-http-port=8545"
      - "--rpc-ws-enabled"
      - "--rpc-ws-host=0.0.0.0"
      - "--rpc-ws-port=8546"
    ports:
      - "8547:8545"
      - "30305:30303"

  besu-bootnode:
    image: hyperledger/besu:latest
    container_name: besu-bootnode
    volumes:
      - ./bootnode:/var/lib/besu
      - ./keys:/opt/keys
      - ./genesis:/opt/genesis
    command:
      - "--genesis-file=/opt/genesis/genesis.json"
      - "--data-path=/var/lib/besu"
      - "--p2p-port=30303"
    ports:
      - "30306:30303"
